// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: Zhaoh0405.proto

/*
Package sample_package_0405 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package sample_package_0405

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_Zhaoh0405_SayHello_0(ctx context.Context, marshaler runtime.Marshaler, client Zhaoh0405Client, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq HelloRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.SayHello(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_Zhaoh0405_SayHello_0(ctx context.Context, marshaler runtime.Marshaler, server Zhaoh0405Server, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq HelloRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.SayHello(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterZhaoh0405HandlerServer registers the http handlers for service Zhaoh0405 to "mux".
// UnaryRPC     :call Zhaoh0405Server directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterZhaoh0405HandlerFromEndpoint instead.
func RegisterZhaoh0405HandlerServer(ctx context.Context, mux *runtime.ServeMux, server Zhaoh0405Server) error {

	mux.Handle("POST", pattern_Zhaoh0405_SayHello_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/sample_module_0405.sample_package_0405.Zhaoh0405/SayHello", runtime.WithHTTPPathPattern("/sample_module_0405.sample_package_0405.Zhaoh0405/SayHello"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_Zhaoh0405_SayHello_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_Zhaoh0405_SayHello_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterZhaoh0405HandlerFromEndpoint is same as RegisterZhaoh0405Handler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterZhaoh0405HandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterZhaoh0405Handler(ctx, mux, conn)
}

// RegisterZhaoh0405Handler registers the http handlers for service Zhaoh0405 to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterZhaoh0405Handler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterZhaoh0405HandlerClient(ctx, mux, NewZhaoh0405Client(conn))
}

// RegisterZhaoh0405HandlerClient registers the http handlers for service Zhaoh0405
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "Zhaoh0405Client".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "Zhaoh0405Client"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "Zhaoh0405Client" to call the correct interceptors.
func RegisterZhaoh0405HandlerClient(ctx context.Context, mux *runtime.ServeMux, client Zhaoh0405Client) error {

	mux.Handle("POST", pattern_Zhaoh0405_SayHello_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/sample_module_0405.sample_package_0405.Zhaoh0405/SayHello", runtime.WithHTTPPathPattern("/sample_module_0405.sample_package_0405.Zhaoh0405/SayHello"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_Zhaoh0405_SayHello_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_Zhaoh0405_SayHello_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_Zhaoh0405_SayHello_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"sample_module_0405.sample_package_0405.Zhaoh0405", "SayHello"}, ""))
)

var (
	forward_Zhaoh0405_SayHello_0 = runtime.ForwardResponseMessage
)
